### ISSUE TITLE
这demo 是用什么编译器。。 目录好奇怪， ADT  android studio 都跑不起来

### ISSUE THREAD

**Issue by YancyYe** [siyanhui/bqmm-demo-android#1]

**Comment by iamlixiao** [comment]
就是个普通的Android Studio项目啊。目录和用Android Studio新建的项目确实不一样，但不会跑不起来。
如果是用Android Studio打开之后报错的话，参照build.gradle里的注释把AppID和AppSecret添加到local.properties里面应该就可以解决。

**Comment by YancyYe** [comment]
刚刚看了下 貌似 和  ADT 的目录相似，，  android studio 导入目录是乱的。。    = =  我现在用笨方法，一个一个复制到新建项目中的  0.0
